# Generated by Django 5.1.1 on 2024-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
