# Generated by Django 5.1.1 on 2024-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_final',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=10),
        ),
    ]
