# Generated by Django 5.1.1 on 2024-12-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_anual_año'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('ingresos', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('gastos', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('ganancia', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(unique=True)),
                ('ingresos', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('gastos', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ganancia', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Reporte_anual',
        ),
        migrations.DeleteModel(
            name='Reporte_mensual',
        ),
    ]
