# Generated by Django 5.1.1 on 2024-10-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_detalleproducto_delete_detallesdecompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra'),
        ),
    ]
