# Generated by Django 5.1.1 on 2024-10-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_detalleproducto_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
