# Generated by Django 5.1.1 on 2024-10-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_alter_detalleproducto_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
